#!/bin/bash


cdir=$PWD

# make field separation based on newline
_ifs="$IFS"
IFS=$'\n'

# iterate over available .git directories
for el in $(find -name '.git')
do
	path=$(dirname $el)
	
	cd $path

	echo -n "$path"
	[ -n "$(git status --porcelain 2>/dev/null)" ] && echo -ne " (\033[36mdirty\033[0m)"
	echo -n ": "

	for remote in $@
	do
		echo -ne "$remote "

		if [ "$(git remote show | grep $remote)" == "" ];then
			echo -ne "\033[33mmissing\033[0m "
			continue
		fi

		msg=$(git remote show $remote 2>/dev/null)

		if [ $? -eq 0 ];then
			if [ "$(echo $msg | grep 'fast-forwardable')" != "" ];then
				echo -ne "\033[33mfast forwardable\033[0m "
			fi

			if [ "$(echo $msg | grep 'out of date')" != "" ];then
				echo -ne "\033[35mout of date\033[0m "
			fi

			if [ "$(echo $msg | grep 'up to date')" != "" ];then
				echo -ne "\033[32mup to date\033[0m "
			fi
		else
			echo -ne "\033[31merror\033[0m "
		fi
	done

	echo
	cd $cdir
done

# restore field separation
IFS="$_ifs"
