#!/bin/bash


remote="home"
cdir=$PWD


if [ $1 ];then
	remote=$1
fi

# make field separation based on newline
_ifs="$IFS"
IFS=$'\n'

# iterate over available .git directories
for el in $(find -name '.git')
do
	path=$(dirname $el)
	printf "%50.50s:" $path
	
	cd $path
	msg=$(git remote show $remote 2>/dev/null)
	e=$?
	cd $cdir

	if [ $e -eq 0 ];then
		if [ "$(echo $msg | grep 'fast-forwardable')" != "" ];then
			echo -ne " \033[33mfast forwardable\033[0m"
		fi

		if [ "$(echo $msg | grep 'out of data')" != "" ];then
			echo -ne " \033[31mout of date\033[0m"
		fi

		if [ "$(echo $msg | grep 'up to date')" != "" ];then
			echo -ne " \033[32mup to date\033[0m"
		fi
	else
		echo -ne " \033[31merror\033[0m"
	fi

	echo
done

# restore field separation
IFS="$_ifs"
