#!/bin/bash

author=$1
email=$2


# require user input [y/N]
# return 0 - yes
#		 1 - no
function yesno(){
	echo $1 " [y/N]"
	read -sn1 x

	if [ "$x" != "y" -a "$x" != "Y" ];then
		exit 0
	fi
}

# main
if [ $# -lt 2 -o "$1" == "-h" -o "$1" == "--help" ];then
	printf "usage: %s <new-author> <new-mail>\n" $0
	exit 0
fi

yesno "changing author and email for complete history"

git filter-branch --env-filter "GIT_AUTHOR_NAME=\"${author}\";GIT_AUTHOR_EMAIL=\"${email}\";GIT_COMMITTER_NAME=\"${author}\";GIT_COMMITTER_EMAIL=\"${email}\";" HEAD
